### PR TITLE
update gentoo installation instructions according to the ebuild changes

### PR DESCRIPTION
**Pull request by NuLL3rr0r**

### CODE REVIEW

**Comment by n-ham** [comment]
It looks like you've just modified the built files and not the content files to build the site with? 

I can probably just merge these changes and add the changes you've made to the content files if you like?

For future reference, try using nsm to clone the site repository, make the changes in the content/template directories. Run nsm build-all or nsm build-updated and make sure everything builds fine (worth viewing the built site locally as well). Then push the changes and put in PR(s). On GitLab which is what Netlify is linked up to there is only one branch so only one merge request is needed. On GitHub there's 2 branches master and stage, so will likely need to put in PRs for both branches. 

I am tempted to link the Netlify site up to the github repo. Though prefer linking Netlify sites up to repos with one branch rather than two. One branch works fine to go with GitLab pages but two branches is what works for GitHub pages. You can just use once branch on GitHub and hook Netlify up to it, but wont work with GitHub pages then (at least I dunno how to use GitHub pages with one branch).

**Comment by n-ham** [comment]
Also with GitHub when you put in a PR, it's worth going in to the settings of your forked repo and enabling GitHub Pages so people can view the changes to the PR. 

If Netlify is linked up to the repo it will provide a preview link with the modified website so that's not needed. And if you're forking a website repo on GitLab it will have a .gitlab-ci.yml file anyway so no need to enable anything, the forked repo should have a link (go to settings->pages to find it).

**Comment by n-ham** [comment]
Oh yeah, when you use `nsm clone` rather than `git clone` it will handle the multiple branch thing for you. Same as using `nsm bcp` rather than `git push`, though you may need to enter username/password twice (I dunno what to do about that).

**Comment by NuLL3rr0r** [comment]
Sorry for the inconvinience. Haven't read the documentation yet.

Thak you for the information.

**Comment by n-ham** [comment]
I just finished updating the content files for each of the mirrors and pushed the changes, should now be live. I didn't notice there wasn't any syntax highlighting on the install pages for the code snippets either, fixed!

**Pull request merged**
